spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    username: "root"
    password: "!QAZxsw2"
    url: jdbc:mysql://127.0.0.1:3306/tanqiu?serverTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  druid: 
    connectionProperties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
    filters: "stat,wall,logback"
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: "SELECT 1 FROM DUAL"
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

mybatis:
  type-aliases-package: com.artqiyi.dao.model

server: 
  port: 80
#  ssl: 
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
#  
